### ISSUE TITLE
Check When Finished on Create and Read Milestone

### ISSUE THREAD

**Issue by Jonathon22** [Jonathon22/lll-Emporium#68]
## Feature Summary
***Finish Create and Read on LLL-Emporium***

- [x] Create on Users 
- [x] Read on Users
- [x] Create on Transaction Types
- [x] Read on Transaction Types
- [x] Create on Products 
- [x] Read on Products
- [x] Create on Categories
- [x] Read on Categories
- [x] Create on Order Lines 
- [x] Read on Order Lines 
- [x] Create on Product Types 
- [x] Read on Product Types
